[package]
name = "gtk-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
gdk4 = "^0"
gio = "^0"
glib = "^0"
gtk4 = "^0"
dirs = "4.0"
regex = "1"
crossbeam-utils = "0.7.2"

[dependencies.adw]
package = "libadwaita"
version = "0.5.3"
features = ["v1_4"]
